# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm ci
- script: |
    npm run build-prod
  displayName: 'npm install ionic and build prod'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'www'
    ArtifactName: 'www'
    publishLocation: 'Container'